server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false 
  datasource:
    url: jdbc:h2:mem:testdb
    username: ifood
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect      
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher